Global client update
Vasar007/FANUC pull request #15
Opened 2017-11-29 19:43 UTC by Vasar007

- Added lots of new modes to control robot;
- Added checking for sending coordinates;
- Added circlic and partial movements;
- Added handler to work with console (optional, can be easy rebuild for anything else);
- Added graphical dependency from latency of robot answers;
- Added lots of operator overloadings for RobotData;
- Expanded library of functions;

2017-12-01 22:25 UTC, ptrdiff requested changes
В целом всё ок, есть пара вопросов и несколько мелких замечаний. Спасибо за работу.

2017-12-01 22:25 UTC, ptrdiff commented on Utilities/Source/Utility.inl
> +inline std::string fromString(const std::string &str, bool &ok)
**(optional,controversial, repeatedly )** Видимо, мы не обсудили в code style то, где ставить &/* в ссылках/указателях.  У тебя то после типа, то перед именем переменной, надо будет обсудить и уже решить, но точно не критично в текущей проверке.

2017-12-01 22:25 UTC, ptrdiff commented on Utilities/Source/Utility.cpp
> +namespace
Интересное использование namespace, даже не смотрел на него в таком ключе.) спасибо.)  в других  cpp такое не заметил, только лишь ради ptr завел?

2017-12-01 22:25 UTC, ptrdiff commented on Utilities/Source/Utility.inl
> +template <class T, class U>
**(optional, repeatedly)** В шаблонах у тебя то typename, то class. На данный момент typename более принят к использованию, а class устарело, по этому лучше переписать на typename.

2017-12-01 22:25 UTC, ptrdiff commented on Utilities/Source/Print.inl
>  #ifdef __clang__
Не замечание, объясни мне пожалуйста для чего тебя здесь ifndef.

2017-12-01 22:25 UTC, ptrdiff commented on StatisticalDisplay/Source/Transmitter.cpp
> +	, _limitY(maxY)
**(controversial)** Я дроблю строку в списке инициализации после запятой, надо обсудить.

2017-12-01 22:25 UTC, ptrdiff commented on SimpleWinsockInterface/Source/WinsockInterface.h
>  #pragma comment (lib, "ws2_32.lib")
**(controversial)** Необходимо обсудить использование pragma comment.

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/RobotData.h
>  struct RobotData
Здесь тебя устраивает, что всё находится в public?

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/RobotData.cpp
>  		cin >> coordinate;
**(optional)** std::cin.

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/Handler.h
> +	enum Coordinate
Почему не enum class ?

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/Handler.cpp
> +#include "Utilities.h"
**(should be changed)** разделить пробелом "Other includes" и ".hpp/.h file corresponding to this .cpp file (if applicable)".

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/Client.h
> +	void		circlicProcessing(const RobotData firstPoint, const RobotData secondPoint,
Возможно ли тут передавать RoboData по ссылке?

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/Client.h
> +	void		partialProcessing(const RobotData firstPoint, const RobotData secondPoint,
И здесь тоже вопрос о передаче по значению. Есть необходимость для этого?

2017-12-01 22:25 UTC, ptrdiff commented on SimpleClient/Source/Client.cpp
> +		getpeername(_socketReceive, reinterpret_cast<SOCKADDR*>(&address),
Для reinterpret_cast есть веские причины?

2017-12-01 22:31 UTC, Vasar007 commented on SimpleClient/Source/Client.cpp
> +		getpeername(_socketReceive, reinterpret_cast<SOCKADDR*>(&address),
Да, это по-другому не кастануть, т.к. тут разные типы, которые эквивалентны, но представляют разные структуры.

2017-12-01 22:40 UTC, Vasar007 commented on SimpleClient/Source/Handler.h
> +	enum Coordinate
В данном случае это просто набор констант. Я посчитал это более лаконичным вариантом, нежели расписывать все координаты как константы.

2017-12-01 22:40 UTC, Vasar007 commented on SimpleClient/Source/RobotData.cpp
>  		cin >> coordinate;
Так там у меня `cin` — это параметр)

2017-12-01 22:41 UTC, Vasar007 commented on SimpleClient/Source/RobotData.h
>  struct RobotData
Да, данная структура нужна для математики векторов + там всего пара методов.

2017-12-01 22:42 UTC, Vasar007 commented on SimpleWinsockInterface/Source/WinsockInterface.h
>  #pragma comment (lib, "ws2_32.lib")
Это уйдёт в историю вместе с WinSock. Было лень в линковщик явно прописывать зависимости, а потом выгребать оттуда весь мусор.

2017-12-01 22:44 UTC, Vasar007 commented on Utilities/Source/Print.inl
>  #ifdef __clang__
Для поддержки кроссплатформенности, ибо на разных компиляторах по разному реализованы функции получения типа данных переменной.

2017-12-01 22:46 UTC, Vasar007 commented on Utilities/Source/Utility.cpp
> +namespace
Здесь анонимный `namespace` используется для одноразовой инициализации `default_random_engine`.

2017-12-01 22:49 UTC, Vasar007 commented on Utilities/Source/Utility.inl
> +template <class T, class U>
Это синонимы. Я привык использовать `class` в тех случаях, когда предполагаю, что функция может принимать пользовательские типы данных, когда же работаю только с примитивами — `typename`. Когда подразумевается использования и пользовательских типов, и примитивов, я использую `typename`. Возможно это переусложнённая система, но в некоторых случаях помогает понять/вспомнить, для чего тут были использованы шаблоны.

2017-12-01 22:51 UTC, Vasar007 commented on Utilities/Source/Utility.inl
> +inline std::string fromString(const std::string &str, bool &ok)
Да, этот момент я упустил, в данном случае использовал пример из одной книжки и не пофиксил). Исправлю. Конечно, я за такой вид: ```int foobar(int& a, int* b);```

2017-12-01 22:51 UTC, Vasar007 commented on StatisticalDisplay/Source/Transmitter.cpp
> +	, _limitY(maxY)
Такое выравнивание, на мой взгляд, удобнее, ибо аргументы могут иметь совершенно разую длину. В таком случае же код смотрится

2017-12-01 22:52 UTC, ptrdiff commented on SimpleClient/Source/Client.cpp
> +		getpeername(_socketReceive, reinterpret_cast<SOCKADDR*>(&address),
Принято

2017-12-01 22:54 UTC, ptrdiff commented on SimpleClient/Source/Handler.h
> +	enum Coordinate
Enum class для строгости более предпочтителен, не вижу смысла в данном случае использовать стандартный enum  без веских причин.

2017-12-01 22:55 UTC, ptrdiff commented on SimpleClient/Source/RobotData.cpp
>  		cin >> coordinate;
Принято, проглядел.)

2017-12-01 22:55 UTC, ptrdiff commented on SimpleClient/Source/RobotData.h
>  struct RobotData
Принято.

2017-12-01 22:55 UTC, ptrdiff commented on SimpleWinsockInterface/Source/WinsockInterface.h
>  #pragma comment (lib, "ws2_32.lib")
Принято, но обсудить и внести в документ надо будет.)

2017-12-01 22:55 UTC, ptrdiff commented on Utilities/Source/Print.inl
>  #ifdef __clang__
Принято.

2017-12-01 22:57 UTC, ptrdiff commented on StatisticalDisplay/Source/Transmitter.cpp
> +	, _limitY(maxY)
Я тебя понял, думаю, это точно надо обсудить с другими и внести в code style.

2017-12-01 22:57 UTC, ptrdiff commented on Utilities/Source/Utility.cpp
> +namespace
Принято.

2017-12-01 22:57 UTC, Vasar007 commented on SimpleClient/Source/Handler.cpp
> +#include "Utilities.h"
**(Fixed)**: У меня как-то странно отрабатывал механизм `std::ref/std::cref` при пересылке параметров через промежуточную функцию, и поток крашился с эксепшеном "Invalid memory access". Сейчас вернул ссылки, пока работает.

2017-12-01 22:57 UTC, Vasar007 commented on SimpleClient/Source/Client.h
> +	void		partialProcessing(const RobotData firstPoint, const RobotData secondPoint,
**(Fixed)**: У меня как-то странно отрабатывал механизм `std::ref/std::cref` при пересылке параметров через промежуточную функцию, и поток крашился с эксепшеном "Invalid memory access". Сейчас вернул ссылки, пока работает.

2017-12-01 23:00 UTC, ptrdiff commented on Utilities/Source/Utility.inl
> +template <class T, class U>
Я понимаю, что это синонимы, но кроме как для объявления шаблонного параметра другого шаблонного параметра нет смысла использовать class.
Если ты считаешь это спорным моментом, то это тоже отправляется в обсуждение.) всё же мы только начали вместе все работать, в начале куча обсуждений неизбежна.)

2017-12-01 23:01 UTC, ptrdiff commented on Utilities/Source/Utility.inl
> +inline std::string fromString(const std::string &str, bool &ok)
Принято, если другие будут не против, так и занесем в code style.

2017-12-01 23:02 UTC, ptrdiff commented on SimpleClient/Source/Client.h
> +	void		partialProcessing(const RobotData firstPoint, const RobotData secondPoint,
Принято, если будет вновь пойман этот bug, то попробуем вместе найти решение.

2017-12-01 23:02 UTC, ptrdiff commented on SimpleClient/Source/Handler.cpp
> +#include "Utilities.h"
Принято, если будет вновь пойман этот bug, то попробуем вместе найти решение.

2017-12-01 23:02 UTC, ptrdiff commented on SimpleClient/Source/Handler.cpp
> +#include "Utilities.h"
Вася, копи - паст, не туда.))

2017-12-01 23:21 UTC, Vasar007 commented on SimpleClient/Source/Handler.cpp
> +#include "Utilities.h"
В плане порядка — да, но его я уже поменял. А вот насчёт пробелов между блоками (тот вариант, что описан в файлике):
```
#include <iostream>
#include <cmath>
// Need to be a space
#include <SFML/Grapchics.hpp>
// Need to be a space
#include "Utilities.h"
#include "Handler.h"
// Need to be a space
// Need to be a space
```

Я так понимаю, нужно попонятнее расписать этот факт?)

2017-12-01 23:24 UTC, Vasar007 commented on SimpleClient/Source/Handler.h
> +	enum Coordinate
Просто если сравнить вот это:
![image](https://user-images.githubusercontent.com/21951872/33507785-be3f298e-d707-11e7-837e-79b9107039ee.png)
и вот это:
![image](https://user-images.githubusercontent.com/21951872/33507795-cedd8768-d707-11e7-9dcd-199470716b58.png)
то мне приглянулся первый вариант)

2017-12-02 00:01 UTC, ptrdiff approved these changes
OK.

2017-12-02 00:03 UTC, merged